Update bootstrap script

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,79 +1,87 @@
 #!/usr/bin/env bash
-#
-# bootstrap installs things.
+
+# Bootstrap all the things.
+
+set -o errexit
+set -o nounset
+set -o pipefail
 
 cd "$(dirname "$0")/.."
-DOTFILES_ROOT=$(pwd -P)
 
-set -e
-
-echo ''
+DOTFILES=$(pwd -P)
+OS=$(uname -s)
 
 info () {
-  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+  printf "\r\e[1m(\e[1;34m..\e[0;1m) %s\e[0m\n" "$1"
 }
 
 user () {
-  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+  printf "\r\e[1m(\e[1;33m??\e[0;1m) %s\e[0m\n" "$1"
 }
 
-success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+okay () {
+  printf "\r\e[1m(\e[1;32mok\e[0;1m) %s\e[0m\n" "$1"
 }
 
 fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
+  printf "\r\e[1m(\e[1;31mxx\e[0;1m) %s\e[0m\n" "$1" && exit 1
 }
 
 setup_gitconfig () {
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
-    info 'set up gitconfig'
+  local template="git/gitconfig.local.symlink.example"
+  local path="git/itconfig.local.symlink"
 
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
+  local credentials
+  local name
+  local email
+
+  if ! [ -f "$path" ]; then
+    info "Setting up git config"
+
+    if [ "$OS" == "Darwin" ]; then
+      credentials="osxkeychain"
+    else
+      credentials="cache"
     fi
 
-    user ' - What is your github author name?'
-    read -e git_authorname
-    user ' - What is your github author email?'
-    read -e git_authoremail
+    user "- What is your GitHub author name?"
+    read -r -e name
 
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
+    user "- What is your GitHub author email?"
+    read -r -e email
 
-    success 'gitconfig'
+    sed \
+      -e "s/AUTHORNAME/$name/g" \
+      -e "s/AUTHOREMAIL/$email/g" \
+      -e "s/GIT_CREDENTIAL_HELPER/$credentials/g" \
+      "$template" \
+      > "$path"
+
+    okay "Created $path"
   fi
 }
-
 
 link_file () {
   local src=$1 dst=$2
 
-  local overwrite= backup= skip=
+  local overwrite=
+  local backup=
+  local skip=
   local action=
 
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-  then
+  if [ -f "$dst" ] || [ -d "$dst" ] || [ -L "$dst" ]; then
+    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]; then
+      local current
+      local action
 
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
+      current="$(readlink "$dst")"
 
-      local currentSrc="$(readlink $dst)"
-
-      if [ "$currentSrc" == "$src" ]
-      then
-
+      if [ "$current" == "$src" ]; then
         skip=true;
-
       else
-
-        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
-        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
+        user "File already exists: $dst ($(basename "$src")). What do you want to do?\n\
+        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, or [B]ackup all?"
+        read -r -n 1 action
 
         case "$action" in
           o )
@@ -91,66 +99,61 @@ link_file () {
           * )
             ;;
         esac
-
       fi
-
     fi
 
     overwrite=${overwrite:-$overwrite_all}
     backup=${backup:-$backup_all}
     skip=${skip:-$skip_all}
 
-    if [ "$overwrite" == "true" ]
-    then
+    if [ "$overwrite" == "true" ]; then
       rm -rf "$dst"
-      success "removed $dst"
+      okay "removed $dst"
     fi
 
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
+    if [ "$backup" == "true" ]; then
+      mv "$dst" "$dst.backup"
+      okay "moved $dst to $dst.backup"
     fi
 
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
+    if [ "$skip" == "true" ]; then
+      okay "skipped $src"
     fi
   fi
 
-  if [ "$skip" != "true" ]  # "false" or empty
-  then
+  if [ "$skip" != "true" ]; then # "false" or empty
     ln -s "$1" "$2"
-    success "linked $1 to $2"
+    okay "linked $1 to $2"
   fi
 }
 
 install_dotfiles () {
-  info 'installing dotfiles'
+  info "Setting up dotfiles"
 
   local overwrite_all=false backup_all=false skip_all=false
 
-  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
-  do
+  for src in $(find -H "$DOTFILES" -maxdepth 2 -name '*.symlink' -not -path '*.git*'); do
     dst="$HOME/.$(basename "${src%.*}")"
     link_file "$src" "$dst"
   done
+
+  okay "Set up dotfiles"
+}
+
+install_software () {
+  # If we're on a Mac, let's install Homebrew and other .
+  if [ "$OS" == "Darwin" ]; then
+    info "Installing dependencies"
+    if source bin/dot | while read -r data; do info "$data"; done; then
+      okay "Dependencies installed"
+    else
+      fail "Error installing dependencies"
+    fi
+  fi
 }
 
 setup_gitconfig
 install_dotfiles
+install_software
 
-# If we're on a Mac, let's install and set up homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot | while read -r data; do info "$data"; done
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
-
-echo ''
-echo '  All installed!'
+printf "\n\e[1mDone.\e[0m\n"
